FROM ubuntu:latest

RUN apt update && apt install -y apache2 tcpdump netcat-openbsd python3 python3-pip python3-websockets iptables 
RUN rm -rf /var/lib/apt/lists/*

COPY blacklist_manager.py /usr/local/bin/blacklist_manager.py
RUN chmod +x /usr/local/bin/blacklist_manager.py

COPY endpoint_setup.sh /usr/local/bin/setup.sh
RUN chmod +x /usr/local/bin/setup.sh

EXPOSE 80

ENTRYPOINT [ "/usr/local/bin/setup.sh" ]
